// Regenerates the UK TV channel seed from the published listings:
//   web/data/tvUK.json    — the canonical static map (editable; byFixture/bySlot
//                           overrides are preserved across regenerations)
//   web/js/tvUK.data.js   — the same data as an ES module, so the Worker can bundle
//                           it without a JSON import (same pattern as annexC.data.js)
//
//   node scripts/gen-tvseed.js            # fetch + parse + write
//   node scripts/gen-tvseed.js --mirror   # offline: just re-mirror json → data.js
//
// The Worker's daily cron re-fetches the same source at runtime and overlays the
// result (KV "tv-listings"), so this seed only needs to be roughly current — it is
// the day-one baseline plus the manual override layer.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseListings, TV_SOURCE_DEFAULT } from "../worker/tv.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const JSON_OUT = resolve(root, "web/data/tvUK.json");
const MODULE_OUT = resolve(root, "web/js/tvUK.data.js");

const prev = existsSync(JSON_OUT) ? JSON.parse(readFileSync(JSON_OUT, "utf8")) : {};

let seed;
if (process.argv.includes("--mirror")) {
  seed = prev;
  if (!seed.listings) { console.error("No web/data/tvUK.json to mirror."); process.exit(1); }
} else {
  const url = process.env.TV_SOURCE_URL || TV_SOURCE_DEFAULT;
  const r = await fetch(url, { headers: { "user-agent": "Mozilla/5.0 (wc26-tracker; tv seed gen)" } });
  if (!r.ok) { console.error(`Fetch failed: ${r.status} ${url}`); process.exit(1); }
  const listings = parseListings(await r.text());
  if (listings.length < 50) { console.error(`Parsed only ${listings.length} listings — markup change? Aborting.`); process.exit(1); }
  seed = {
    updated: new Date().toISOString().slice(0, 10),
    source: url,
    note: "UK channels from the BBC/ITV published schedules. The Worker re-checks this source daily and overlays corrections/gap-fills via KV; byFixture (fixture id) and bySlot (e.g. R32-M73) are manual overrides that always win.",
    byFixture: prev.byFixture || {},
    bySlot: prev.bySlot || {},
    listings,
  };
  writeFileSync(JSON_OUT, JSON.stringify(seed, null, 2) + "\n");
  console.log(`Wrote ${JSON_OUT} (${listings.length} listings, ${listings.filter((l) => l.channel).length} with a channel)`);
}

writeFileSync(MODULE_OUT, `// GENERATED by scripts/gen-tvseed.js — mirror of web/data/tvUK.json (do not edit)\nexport default ${JSON.stringify(seed)};\n`);
console.log(`Wrote ${MODULE_OUT}`);
